apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
      - name: store-app
        image: vishnugpd/store-app
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: store-app
spec:
  selector:
    app: store-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
